extends:
  - airbnb-base
  - plugin:flowtype/recommended
  - plugin:jest/recommended

parser: babel-eslint

plugins:
  - flowtype
  - jest

globals:
  atom: true
  document: false

env:
  node: true
  jest: true

rules:
  no-mixed-operators: 0 # incompatible with prettier
  no-confusing-arrow: 0 # not that confusing
  max-len:
    - 2
    - 110
